spring:
  application:
    name: auth-service

google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID}

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
